### ISSUE TITLE
azuread_directory_role_assignment keeps getting destroyed/created 

### ISSUE THREAD

**Issue by Geolonmi** [hashicorp/terraform-provider-azuread#1068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

provider azuread 2.37.0
on windows_amd64

### Affected Resource(s)

* `azuread_directory_role_assignment`

### Terraform Configuration Files

```hcl
resource "azuread_directory_role" "privileged_authentication_administrator" {
  provider          = azuread.iso
  display_name  = "Privileged Authentication Administrator" // 7be44c8a-adaf-4e2a-84d6-ab2649e08a13
}
resource "azuread_directory_role_assignment" "example_api_privileged_authentication_administrator" {
  provider            = azuread.iso
  role_id             = azuread_directory_role.privileged_authentication_administrator.object_id
  principal_object_id = azuread_service_principal.example_api.object_id
}
```
### Expected Behavior

When running terraform apply, the role should be assigned to my service principal and then I should be able to run terraform apply again and see an empty plan

### Actual Behavior

There is no errors when applying the plan and the role is correctly assigned to my service app however if I run terraform apply again terraform always want to destroy/recreate the azuread_directory_role_assignment.
I tried to apply the new plan (no matter how many times I apply it), but terraform always want to reproduce the same plan : 

[terraform plan](https://gist.github.com/Geolonmi/a40a4fc2e37a77ce982771ac04db06ae)

### Steps to Reproduce

1. `terraform apply`

**Comment by manicminer** [comment]
Hi @Geolonmi, thanks for opening this issue. I believe the problem lies with your configuration - as per the documentation for this resource, you will need to reference the `template_id` attribute from the `azuread_directory_role` resource in the `role_id` property of the `azuread_directory_role_assignment` resource, rather than the `object_id` attribute as shown in your config snippet. Whilst the API does accept the object ID of the instantiated role, it populates the role assignment using the template ID of the role. This is unfortunately not super intuitive but is due to the way built-in roles are implemented in the service, and exposed in the API.

I believe making this change will resolve this issue for you, so I'll close the issue for now. However, if you are still experiencing this persistent diff, please comment further with the details and I'll be happy to take another look.
