### ISSUE TITLE
Support import of `azuread_application_password` for Azure

### ISSUE THREAD

**Issue by serhatataman** [hashicorp/terraform-provider-azuread#1118]
In your documentation it is mentioned that we can import `azuread_application_password`. However, when I try to import my `azuread_application_password` like so `terraform import azuread_application_password.client_secret [AppObjectId]/password/[PasswordId]` I get `**Error**: resource azuread_application_password doesn't support import`. Is the command not supported or the documentation is deceiving?

**Comment by nbaju1** [comment]
Where does it state that you can import an application secret?

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_password#import

**Comment by manicminer** [comment]
Hi @serhatataman, we specifically state for `azuread_application_password` that "This resource does not support importing". This is an API limitation, and a very sensible one, as the API will not return a password value after its initial creation. Along the same line, we also cannot specify the password value as it is generated by the API, so for this particular resource there is no other option but to create a new password in order to bring it under Terraform management.
