### ISSUE TITLE
Error: `mail_nickname` is required for mail-enabled groups

### ISSUE THREAD

**Issue by DeviaVir** [hashicorp/terraform-provider-azuread#1259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

* Terraform v1.6.4
* AzureAD v2.46.0

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "admin_group" {
  display_name     = "test"
  mail_enabled     = true
  mail_nickname    = "testGroup"
  security_enabled = true
  types            = ["Unified"]
}
```

### Debug Output

Plan failed:

```
Error: `mail_nickname` is required for mail-enabled groups
```

### Panic Output

N/A

### Expected Behavior

Expected plan to succeed and show it was going to create the AzureAD group.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

### References

* [group_resource.go relevant logic](https://github.com/hashicorp/terraform-provider-azuread/blob/main/internal/services/groups/group_resource.go#L390) - could it be that the diff produces no result because there's no value yet if the resource hasn't been created yet?

**Comment by manicminer** [comment]
@DeviaVir Thanks for reporting this, and for opening [the related PR](https://github.com/hashicorp/terraform-provider-azuread/pull/1260). Unfortunately as this is a required field for mail-enabled groups, we cannot make this optional. I've explained in more detail in my comment on your PR, but you might want to look at the [`ignore_changes` lifecycle meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes).

Since there's nothing for us to do here, as we match the API behavior in our validation, I'm going to close out this issue for now. Thanks!

**Comment by DeviaVir** [comment]
@manicminer up to you, but I am not making the field optional. Rather, there seems to be an issue with detecting a diff, while the only reason we are looking to compare is to figure out if it's empty and then return that error. In other places of the logic, we are just setting a default value. My proposal here is to if the mail_nickname is empty, is to just generate it for the user.
