### ISSUE TITLE
Failed to set `external_senders_allowed` for group with object ID

### ISSUE THREAD

**Issue by jempson** [hashicorp/terraform-provider-azuread#1262]
When attempting to migrate a DL to a Unified M365 group I received the following error message.

╷
│ Error: Failed to set `external_senders_allowed` for group with object ID "<id>"
│ 
│   with azuread_group.cloud,
│   on dl_groups.tf line 1, in resource "azuread_group" "cloud":
│    1: resource "azuread_group" "cloud" {
│ 
│ GroupsClient.BaseClient.Patch(): unexpected status 403 with OData error:
│ ErrorGroupsAccessDenied: User does not have permissions to execute this
│ action.
╵
My API permissions include Group.ReadWrite.All and I'm able to create this group if I remove the external_senders_allowed option from my terraform code?  I was setting this to the default of false.  I also received the same error message after rmoving on the auto_subscribe_new_members option which was also set to the default of false.  These two options were set in preparation for a group which will have both of these options set to true.  

What permissions need to be granted with in the service principal to allow the settings of these two options.  My assumption was Group.ReadWrite.All was all that was required to create groups with in Entra ID.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Hi @jempson, thanks for reporting this issue. This is unfortunately an API bug (or feature maybe), where certain [M365 related] properties can only be set when authenticating as a user principal - i.e. service principal roles/scopes are not supported. This is [documented for the `azuread_group` resource](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group) under the Permissions section of that page.

As this is due to an API limitation, there's unfortunately nothing we can do here. If you need to manage these properties with Terraform, you will have to use the Azure CLI to authenticate as a user.

Since this is not an issue with the provider, I'm going to close this issue out, however please feel free to comment further if I have misunderstood your report, and I'll be happy to take another look. Thanks!
