### ISSUE TITLE
Add and grand admin consent for the "Azure VPN" enterprise application

### ISSUE THREAD

**Issue by samuelb** [hashicorp/terraform-provider-azuread#1341]
Hello

I want to add and grant consent of the "Azure VPN" enterprise application as described at https://learn.microsoft.com/en-us/azure/virtual-wan/openvpn-azure-ad-tenant#enable-authentication by using Terraform. Additionally, I aim to manage its users and groups using Terraform too. However, I couldn't figure out how to express this in Terraform.

As I understood it, this Azure VPN enterprise application is neither a application template nor a new application I'm create in my Entra ID. It's some existing application within Azure where I don't know how to write the Terraform code to address it.

Any guidance or insights on how to achieve this would be greatly appreciated. Thanks!

**Comment by manicminer** [comment]
Hi @samuelb, thanks for opening this issue. Normally we ask that usage questions are raised on our [Discuss](https://discuss.hashicorp.com/c/terraform-core/27) site or in our community Slack org (details in the project readme).

However I believe all you'll need is to use the [`azuread_app_role_assignment`](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/app_role_assignment#example-usage) resource. The first example in the docs, titled _App role assignment for accessing Microsoft Graph_ should be more or less transferable, you will need the client ID of the Azure VPN application which you can get from the data source in the example where it's called "AzureVPN", e.g. `data.azuread_application_published_app_ids.well_known.result.AzureVPN`.

Since, as mentioned above, this is more of a usage question and we try to keep GitHub issues for bug reports & feature requests, I'll close out this issue - but you are welcome to join our Slack group where you'll likely get quicker answers for any usage questions :)
