### ISSUE TITLE
Plan does not see any changes if app_role is deleted from azuread_application

### ISSUE THREAD

**Issue by FaouziK** [hashicorp/terraform-provider-azuread#328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.13.3
Provider Azure AD v1.0.0

### Affected Resource(s)

* `azuread_application`

### Expected Behavior

Deleting the app_role in the resource azuread_application

### Actual Behavior

No changes seeing on terraform plan neither terraform apply

### Steps to Reproduce

1. `terraform apply` with an azuread_application which has app_role 
2. delete app_role from the azuread_application resource
2. `terraform plan`

The azuread_application has always app_role in its structure

**Comment by manicminer** [comment]
Hi @FaouziK, thanks for raising this. Many attributes of resources in this provider are computed, to accommodate workflows where some objects are managed in multiple places. The `app_role` attribute of azuread_application is one of those. In order to ensure no app roles, you'll need to explicitly specify an empty list. e.g.

```hcl
resource "azuread_application" "test" {
  name = "testApp"
  app_role = []
```

Can you give this a try and see if it works for you?

**Comment by FaouziK** [comment]
Hi Manicminer,

I just try this with terraform plan and the result is : 
`Error: Unsupported argument

  on ../../main.tf line 99, in resource "azuread_application" "register_application":
  99:   app_role = []

An argument named "app_role" is not expected here. Did you mean to define a
block of type "app_role"?`

I also try with app_role {} but here again the result is : 
`Error: Unsupported argument

  on ../../main.tf line 99, in resource "azuread_application" "register_application":
  99:   app_role = []

An argument named "app_role" is not expected here. Did you mean to define a
block of type "app_role"?`

In fact, with the provider version, I try to extract app_role from azurad_application resource into the new azuread_application_app_role resource, but terraform can't see any change with this and crash with duplicate values error.

**Comment by manicminer** [comment]
Hi @FaouziK, thanks for testing and clarifying. This looks like a bug, we'll look into it.

**Comment by twendt** [comment]
I just ran into this issue as well. Is there any update?

I added 4 roles initially and wanted to delete all of them. It does not pick up the change. I can however delete entries as long as I leave at least one entry in the list.

I do not understand the suggestion above since app_role is a block and not an attribute. Is there another way to explicitly define an empty list here apart from removing all blocks?

**Comment by manicminer** [comment]
It is a block, but it has `ConfigMode: schema.SchemaConfigModeAttr` set in the schema so it should be possible to specify it like an attribute, for example `app_role = []`. This is handled by the provider SDK but has been somewhat hit and miss.

We'll be addressing this in the next major version of the provider where it will most likely be a breaking change, but greatly improving on the current schema.
