### ISSUE TITLE
Azure AD application Certificate

### ISSUE THREAD

**Issue by sahityamalepati** [hashicorp/terraform-provider-azuread#400]
I am trying to create  AD application certificate getting cert from Keyvault using below code but i am getting error as invalid key though i didnt pass any key. COuld you please help me to resolve this. I have created SSL certificate in my desktop and tried using it .

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

data "azurerm_resource_group" "rg" {
   name = var.resource_group_name
 }

data "azurerm_key_vault" "app_vault" {
   name = var.azurerm_key_vault
   resource_group_name = var.resource_group_name
}

resource "azuread_application" "example" {
  display_name               = "myappTest6"
  homepage                   = "http://myhomepage3"
  identifier_uris            = ["http://contosotest123.com"]
  reply_urls                 = ["http://contosotest123.com"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = true
}

resource "azuread_service_principal" "myapp" {
  application_id               = azuread_application.example.application_id
  app_role_assignment_required = false
}

resource "azurerm_key_vault_certificate" "example" {
  name         = "imported-certificatenew"
  key_vault_id = data.azurerm_key_vault.app_vault.id

  certificate {
    contents = filebase64("sslcert.pfx")
    password = "test@123"
  }

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
}

resource "azuread_application_certificate" "example" {
  application_object_id = azuread_application.example.id
  type                  = "AsymmetricX509Cert"
  value                 = azurerm_key_vault_certificate.example.id
  end_date              = azurerm_key_vault_certificate.example.certificate_attribute[0].expires
  start_date            = azurerm_key_vault_certificate.example.certificate_attribute[0].not_before
}
```

#Error: 
Error: Creating certificate credentials "e5051f8b-0c76-810d-1a9c-df22ae0c3815" for application with object ID "0d5b44b2-6145-4e51-ae70-cb350af5ae64"

graphrbac.ApplicationsClient#UpdateKeyCredentials: Failure responding to
request: StatusCode=400 -- Original Error: autorest/azure: Service returned an
error. Status=400 Code="Unknown" Message="Unknown service error"
Details=[{"odata.error":{"code":"Request_BadRequest","date":"2021-02-12T09:44:28","message":{"lang":"en","value":"Invalid
certificate: Key value is invalid
certificate"},"requestId":"af87a866-3346-4599-a4ef-49a23f45a26e","values":[{"item":"PropertyName","value":"keyCredentials.value"},{"item":"PropertyErrorCode","value":"InvalidKeyValue"}]}}]

****

**Comment by manicminer** [comment]
Hi @sahityamalepati, this looks like an error in your configuration. You have used the `id` attribute from the azurerm_key_vault_certificate resource when I believe you likely want the `certificate_data` or `certificate_data_base64` attributes. There is an example in the docs for [azuread_application_certificate](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_certificate) which shows this.

Additionally, I'd recommend using the `object_id` attribute of the azuread_application resource rather than the `id` attribute, as the latter may change over time whereas the former is guaranteed to always return the object ID.

Since this is more of a usage question, I'd suggest pursuing further help via the [Azure Providers category](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) in the [HashiCorp Discuss](https://discuss.hashicorp.com/) forums, as it will help us to keep this issue tracker focused on feature requests and bug reports. Thanks!
