### ISSUE TITLE
Make azuread_application resource and datasource have same property for application roles.

### ISSUE THREAD

**Issue by magne** [hashicorp/terraform-provider-azuread#402]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `azuread_application` resource uses `app_role` for application roles, while the corresponding data source uses `app_roles`. This makes them non-interchangable. The `oauth2_permissions`, on the other hand, is the same in both the resource and the data source.

Please create a property `app_roles` in the `azuread_application` resouce, and deprecate property `app_role`.

### New or Affected Resource(s)

* azuread_application

**Comment by manicminer** [comment]
Hi @magne, thanks for raising this.

The difference in pluralization between the resource and data source owes its heritage to the slightly different representation. Whilst the data source exports a list, in the resource both app roles and oauth2 permission scopes are configured as blocks and represented as sets. This means they are not interchangeable even if they were to share the same attribute name.

You are correct, there is a naming disparity, but it's actually with `oauth2_permissions` [in the resource] which we are planning to rename to `oauth2_permission_scope` [singular] in v2.0. We're also looking at exporting complex attributes like these in different ways to make it easier to consume them. One common pattern, for example, is to look up roles/scopes by name to retrieve the uuid, and we're thinking that a map of [role/scope name] => uuid would be useful.

This issue seems like a great place to track this, so I'll happily keep it open for that purpose.

**Comment by manicminer** [comment]
These changes have now been merged in preparation for version 2.0.0. Both the resource and data source now expose an `api` block. In the resource, there is a nested `oauth2_permission_scope` block and in the data source, there is an `oauth2_permission_scopes` list inside the `api` block. The resource continues to expose an `app_role` block and the data source an `app_roles` list.

Both the resource and data source additionally now export two computed attributes `app_role_ids` and `oauth2_permission_scope_ids`. These are maps indexed by role or scope name respectively, and having the role/scope UUID as values.

The above changes are reflected in the latest [documentation for the resource](https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/resources/application.md) and [data source](https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/data-sources/application.md).
