### ISSUE TITLE
Error: Failed to install provider

### ISSUE THREAD

**Issue by IanMoroney** [hashicorp/terraform-provider-azuread#405]
Just started happening, happens with all providers, both locally and in terraform cloud.
Terraform registry gone down maybe?

Error: Failed to install provider

Error while installing hashicorp/azurerm v2.31.1: could not query provider
registry for registry.terraform.io/hashicorp/azurerm: failed to retrieve
authentication checksums for provider: 403 Forbidden

**Comment by manicminer** [comment]
Hi @IanMoroney, thanks for reporting this service issue. Our operations engineering team is aware of the issue and is currently working on remediation. I believe a fix should be forthcoming very soon. Since this is more of a service issue that is affecting multiple providers, I'm going to close this for now but please continue to check as a solution is being worked on. Thanks!

**Comment by manicminer** [comment]
I believe the outage has been largely resolved, sorry for the inconvenience here. There may be some residual caching issues but please continue to try downloading.

**Comment by IanMoroney** [comment]
Any root cause info available?

**Comment by katbyte** [comment]
I believe the public incident page for this incident can be found here: https://status.hashicorp.com/incidents/68jxtclzwn33

**Comment by IanMoroney** [comment]
Sadly the root cause wasn't communicated :/
