### ISSUE TITLE
[Service Principal] [azuread_service_principal] Declaration of existent SP with application_id

### ISSUE THREAD

**Issue by JeremyBouchet** [hashicorp/terraform-provider-azuread#416]
Hello,

in my terraform file for Velero I want to declare an existent Service Principal with the existent application_id but it seems that is not taken into account.

My Terraform code :
```hcl
resource "azuread_service_principal" "velero" {
  application_id = "xxxxxxx"
}

resource "azuread_service_principal_password" "velero" {
  service_principal_id = azuread_service_principal.velero.application_id

  value                = random_string.password_velero.result
  end_date             = "2050-01-01T01:02:03Z"
}
```

Is my above declaration is correct ?

Do you have examples of Terraform code to declare existent Service Principal with existent application_id ?

thank you in advance,

**Comment by manicminer** [comment]
Hi @JeremyBouchet, by existent do you mean the application already exists? Or the service principal? If you need to look up the application ID, or the object ID of either of those, you likely want to make use of one of the data sources instead of the corresponding resource.

In your snippet, the value for `service_principal_id` in the azuread_service_principal_password resource is incorrect. You'll want to reference the service principal's object ID like this:

```hcl
resource "azuread_service_principal_password" "velero" {
  service_principal_id = azuread_service_principal.velero.object_id
  value                = random_string.password_velero.result
  end_date             = "2050-01-01T01:02:03Z"
}
```

**Comment by JeremyBouchet** [comment]
Hello@manicminer , yes exactly the Service Principal already exists.

thank you for your suggestion, I fixed my resource "azuread_service_principal_password" with "object_id".

I have again a problem to declare the existent Service Principal with the below "data" structures :  

# myCode

resource "random_string" "password_velero" {
    length = 32
    special = false
}

data "azuread_application" "velero" {
    display_name                  = "**DAS-SP-LBN_Velero-AD-App-PRD-clu02**"
}

data "azuread_service_principal" "velero" {
    depends_on           = [data.azuread_application.velero]
  
   #Service Principal "**DAS-SP-LBN_Velero-AD-App-PRD-clu02**"
    application_id       = "XXX-XXX-4222-XXX-XXX"
}

resource "azuread_service_principal_password" "velero" {
    service_principal_id = data.azuread_service_principal.velero.object_id

    value                = random_string.password_velero.result
    end_date             = "2050-01-01T01:02:03Z"
}


# Terraform return me the error : 
"
**Error: Multiple applications found
Found multiple applications matching filter:
displayName eq 'DAS-SP-LBN_Velero-AD-App-int-clu02'**
"

# How to :

It seems that I obliged to use both data types with "azuread_application" and "azuread_service_principal".
But on one side the "application_id" of the existent SP is not an argument of "azuread_application" and when I try to linked the "data.azuread_service_principal.velero" to "data.azuread_application.velero" that returns me that there are multiple applications found with the displayName "DAS-SP-LBN_Velero-AD-App-int-clu02"

How I can implement that ?

**Comment by manicminer** [comment]
@JeremyBouchet The display name of applications is not a unique field, it's up to you to maintain uniqueness if that's how you want to identify your app registrations. You will need to look it up by its application ID (client ID) or object ID. I'd suggest looking at your app registration and service principal in the portal to note which IDs are which (both the app and SP have an object ID but these are different).

**Comment by JeremyBouchet** [comment]
As you I advised me in my resource "azuread_service_principal_password.velero" I changed the variable "service_principal_id" from "_data.azuread_service_principal.velero.application_id_" to "**690d4d49-0c97-4222-8f12-9d32a9ed5e67**" (So with the real Application id).

## my code :

data "azuread_service_principal" "velero" {
  depends_on           = [data.azuread_application.velero]
}

resource "azuread_service_principal_password" "velero" {
  **service_principal_id = "690d4d49-0c97-4222-8f12-9d32a9ed5e67"**

  value                = random_string.password_velero.result
  end_date             = "2050-01-01T01:02:03Z"
}

resource "azurerm_role_assignment" "velero_contributor_role_assignment" {
  scope                = data.azurerm_subscription.current.id
  role_definition_name = "Contributor"

  principal_id         = data.azuread_service_principal.velero.id
  depends_on           = [azuread_service_principal_password.velero]
}

## Result :
But that return me the same error with : 
**Found multiple applications matching filter: "displayName eq 'DAS-SP-LBN_Velero-AD-App-int-clu02'"**

**Comment by manicminer** [comment]
Hi @JeremyBouchet, the service principal object ID isn't the same value as the application ID. It's very understandable to get these mixed up - this can quickly get confusing due to the way it is structured in Azure Active Directory! Also, it looks like there are some pieces missing from the last config you posted. As I mentioned earlier the error you're getting is because you're attempting to look up an application (or its service principal) by display name, but you have more than one application that has the same name - this is possible because the display name isn't a unique property in AAD.

I do appreciate the difficulty and we'd like to help where we can, however this is more of a usage question than a feature request or bug report, and I believe you would be better served by asking your question in one of our community forums. The [HashiCorp Discuss](https://discuss.hashicorp.com/) forum has a dedicated [Azure category](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where other users would also be in a position to offer advice on your configuration.

As such I'm going to close this issue for now, but please feel free to open another issue if you think you have found a bug or have an idea for a feature request. Thanks!
