### ISSUE TITLE
Terraform "Object_id" VS "objectId" of 'az ad app' command

### ISSUE THREAD

**Issue by JeremyBouchet** [hashicorp/terraform-provider-azuread#421]
For a specific Service Principal I remarks that I don't get the same value on Terraform side (in terraform.tfstate) and on "az ad app" Azure command.

- On Terraform side I get that :
The object_Id is **4d468e78-b8fe-4d6f-917f-7feabab4332a** 

```hcl
{
      "module": "module.aks_02",
      "mode": "managed",
      "type": "azuread_service_principal",
      "name": "aks_ad_app",
      "provider": "provider[\"registry.terraform.io/hashicorp/azuread\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "app_role_assignment_required": false,
            "app_roles": [],
            "application_id": "737ffe3f-3430-4230-9924-301a245724ef",
            "display_name": "DAS-SP-int_AKS-AD-App-int-clu02",
            "id": "4d468e78-b8fe-4d6f-917f-7feabab4332a",
            "oauth2_permissions": [
              {
                ...
              }
            ],
            "object_id": "4d468e78-b8fe-4d6f-917f-7feabab4332a",
            "tags": null
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "module.aks_02.azuread_application.aks_ad_app"
          ]
        }
      ]
}
```

- With the command "_az ad app show --id 737ffe3f-3430-4230-9924-301a245724ef_" I get that :
The objectId is **3b70db3e-2069-4f1e-a1ff-907e555a8a68**

```json                                                                                                                                                                       {
  "acceptMappedClaims": null,
  "addIns": [],
  "allowGuestsSignIn": null,
  "allowPassthroughUsers": null,
  "appId": "737ffe3f-3430-4230-9924-301a245724ef",
  "appLogoUrl": null,
  "appPermissions": null,
  "appRoles": [],
  "applicationTemplateId": null,
  "availableToOtherTenants": false,
  "deletionTimestamp": null,
  "displayName": "DAS-SP-int_AKS-AD-App-int-clu02",
  "errorUrl": null,
  "groupMembershipClaims": null,
  "homepage": null,
  "identifierUris": [],
  "informationalUrls": {
    "marketing": null,
    "privacy": null,
    "support": null,
    "termsOfService": null
  },
  "isDeviceOnlyAuthSupported": null,
  "keyCredentials": [],
  "knownClientApplications": [],
  "logo@odata.mediaEditLink": "directoryObjects/3b70db3e-2069-4f1e-a1ff-907e555a8a68/Microsoft.DirectoryServices.Application/logo",
  "logoUrl": null,
  "logoutUrl": null,
  "mainLogo@odata.mediaEditLink": "directoryObjects/3b70db3e-2069-4f1e-a1ff-907e555a8a68/Microsoft.DirectoryServices.Application/mainLogo",
  "oauth2AllowIdTokenImplicitFlow": true,
  "oauth2AllowImplicitFlow": false,
  "oauth2AllowUrlPathMatching": false,
  "oauth2Permissions": [
    {
      ...
   }
  ],
  "oauth2RequirePostResponse": false,
  "objectId": "3b70db3e-2069-4f1e-a1ff-907e555a8a68",
  "objectType": "Application",
```

Is it normal or is there a bug ?

**Comment by manicminer** [comment]
Hi @JeremyBouchet, you are querying for a different object in your az-cli command. You probably want: 
```shell
az ad sp show --id 4d468e78-b8fe-4d6f-917f-7feabab4332a
```

Applications and Service Principals, although related, are distinct object types. There is a [good article in the Azure docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals) which explains the difference between these object types and how they work together.

For general usage questions like this and clarification about how the provider works with Azure Active Directory, we generally ask that you use our community Slack org (link in the readme) or [HashiCorp Discuss](https://discuss.hashicorp.com/) where there is a dedicated [Azure category](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34), as we try to reserve GitHub issues for bug reports and feature requests since this helps us focus development.

I'm going to close this one for now, but if you have any feature requests or come across any suspected bugs, please feel free to open other issues for those, thanks!
