### ISSUE TITLE
Add support for missing AAD columns

### ISSUE THREAD

**Issue by nitmatgeo** [hashicorp/terraform-provider-azuread#433]
Currently Terrfaorm supports only limited fields as [mentioned here](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/user). Why not add support for other missed fields like- FirstName, LastName, emailID, UserType, JobTitle, Department, EmployeeID, Manager, Company, UsageLocation, Alternative email, etc.? 
![image](https://user-images.githubusercontent.com/71626368/118225489-dff4dc00-b4a2-11eb-84a6-94f095626035.png)

This will help to eliminate dependency with AzCLI etc. and should be easy for your developers to include these additional parameters, right?

**Comment by manicminer** [comment]
Hi @nitmatgeo, thanks for the feature request!

We do already support most of these fields - the azuread_user resource has the `given_name`, `surname`, `job_title`, `department`, `company_name`, `usage_location` and `mail_nickname`. In addition there is the `email` attribute, which is read-only at the moment.

The main reason we do not yet support other fields, including complex fields like Manager or User Type, is that the API we use does not support them. For example, Manager is a reference field that refers to another directory object, and User Type requires additional steps for guest users that the current API doesn't perform, which creates broken guest accounts.

The AzureAD provider is transitioning to the newer Microsoft Graph API, which once complete will put us in a much better position to implement these features. This work is ongoing with updates being posted on #323. If you are interested in seeing expanded support for addition user fields, I recommend subscribing to that issue.

In the meantime, I'm going to close this issue since it's not clear what is being asked for - as mentioned we do already support a lot of these fields. However you are very welcome to open another issue requesting support for specific fields or features, which will enable other users to upvote your request and helps us to track ongoing work. Thanks!

**Comment by nitmatgeo** [comment]
@manicminer  Is it possible to have email field now? Since v1.5 is released and we are hopefully nearing v2. Any update please?

**Comment by manicminer** [comment]
@nitmatgeo It's possible we may be able to support the `mail` field in v2.0, although not earlier. I've opened a new issue #452 to track this.
