### ISSUE TITLE
destoy/create for AAD app password with MS Graph API beta

### ISSUE THREAD

**Issue by mhennecke** [hashicorp/terraform-provider-azuread#438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.57.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/winebarrel/mysql v1.10.3

### Affected Resource(s)

* `azuread_application_password`

### Terraform Configuration Files

```hcl
resource "azuread_application_password" "secret" {
  application_object_id = azuread_application.someapp.id
  description           = "client secret"
  value                 = "some-password-coming-from-a-random_password-resource"
  end_date              = "2099-01-01T01:02:03Z"
}
```

### Expected Behavior

The application password description attribute should be refreshed from the azure ad app and no change should happen on the app after azuread provider update.

### Actual Behavior

Resource must be replaced and provider wants to add description, which was already set on the resource before the provider update

```
  # azuread_application_password.secret must be replaced
-/+ resource "azuread_application_password" "secret" {
      + description           = "client secret" # forces replacement
      + display_name          = (known after apply)
      ~ id                    = "guidv4/password/guidv4" -> (known after apply)
      ~ key_id                = "guidv4" -> (known after apply)
      ~ start_date            = "2021-01-22T01:17:37Z" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. Create an Azure AD application secret with a description on provider version 1.4.0
2. Update Azure AD provider to 1.5.0 and activate beta support for MS Graph API `use_microsoft_graph = true`
3. `terraform plan`

**Comment by manicminer** [comment]
Hi @mhennecke, thanks for reporting this unexpected behavior. Unfortunately due to differences between AAD Graph and MS Graph, we've had to make some changes to the `azuread_application_password` and `service_principal_password` resources. These are documented in the [Migration Guide](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/microsoft-graph#resource-azuread_application_password) (and to an extent in the [resource docs](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_password#argument-reference)), but in short the only property that is valid with MS Graph is `application_object_id`. `key_id` and `value` are no longer supported, and contrary to API documentation, `start_date`, `end_date` and `display_name` (`description`) are ignored by the API.

I agree that proposing a replacement for the password isn't very intuitive, unfortunately we've had to strike a balance in order to support both APIs using the same schema. If you were to go ahead and apply the proposed plan, it would actualy fail to recreate the password due to the aforementioned field changes. However, if you remove all the properties from your `azuread_application_password` resource(s) except for `application_object_id`, you should find that Terraform no longer proposes changes to the password resource (although you may find a refresh is needed, but no changes should be made).

Could you give this a go and advise whether that resolves the unwanted diff?

I will look at updating the resource docs to clarify these differences.

**Comment by mhennecke** [comment]
Hi, thanks for the really fast response. Removing `description` fixes the destroy/create issue. Additionally, removing `value` and `end-date` lead to a clean plan without any resource changes, as suggested.

A clarification in the docs is appreciated.
