### ISSUE TITLE
oauth2_permission_scope requires field id

### ISSUE THREAD

**Issue by Theuno** [hashicorp/terraform-provider-azuread#442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
**Terraform v0.14.9**
provider registry.terraform.io/hashicorp/**azuread v1.5.0**

### Affected Resource(s)

* `azuread_application `

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
      version = "1.5.0"
    }
  }
}

provider "azuread" {
  # Configuration options
}

data "azuread_client_config" "current" {}

resource "azuread_application" "bugDemo1" {
  display_name = "bugDemo1"
  prevent_duplicate_names = true

  api {
    oauth2_permission_scope {
      admin_consent_display_name = "Allow User Impersonation"
      // id                         = "000-000-000"
      type                       = "Admin"
      user_consent_description   = "Enables the client application to call the Contacts API on your behalf"
      user_consent_display_name  = "Allow User Impersonation"
      value                      = "access_as_user"
    }
  }
}
```

### Expected Behavior

As the ID is not known before creation of the oauth2_permission_scope, it is not expected that this is a *required* parameter in this context.

### Actual Behavior

Can't create a scope without the id setting, using a generated id doesn't work.
Using 1.4.0 of the azuread plugin, with `oauth2_permissions` the id field is not required.

### Steps to Reproduce

1. `terraform apply` without an id.

### Important Factoids

n/a

### References

n/a

**Comment by manicminer** [comment]
Hi @Theuno, thanks for raising this issue!

We made this change in order to overcome a conflict between Terraform schema limitations and the specific API semantics. Previously we'd generate a UUID and send that in the API request, however in the new `oauth2_permission_scope` block you'll need to specify a UUID. It can be any valid UUID, as long as it's unique inside your _tenant_.

We suggest UUID4 and Terraform does offer a way to generate them for you using the `random_uuid` resource. You can find an example of this [in the Upgrade Guide](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/microsoft-graph#new-required-uuid-fields), however it could probably be more prominent with this information in the resource documentation too. You could also just generate a UUID and paste it into your Terraform config as the value for `id`.

It's also worth noting that specifying a UUID gives you more flexibility and enables some more complex configurations that we previously could not support due to the `id` field being read-only (computed).

I'm going to mark this as a documentation issue and I'll make sure to improve the `azuread_application` resource documentation with this information. Thanks again!
