### ISSUE TITLE
Importing azuread_application_password

### ISSUE THREAD

**Issue by hbuckle** [hashicorp/terraform-provider-azuread#467]
The upgrade guide says

> The key_id field will become read-only as Azure Active Directory no longer allows user-specified key IDs for passwords. This also means that the azuread_application_password resource no longer supports importing in version 2.0 of the provider.

I'm a bit confused why the key_id being read-only means the resource can't be imported, we don't specify the object_id for applications but they can be imported fine?

**Comment by manicminer** [comment]
@hbuckle It's more of a combination of the key ID and the password value itself now being read-only. The password is not returned by the API except for one single time when it is created, so importing it would yield a password with no value. I'll look at clarifying the docs around this.

**Comment by hbuckle** [comment]
OK, it would still be nice to be able to import them, even if it means Terraform has to set a new value for the password. I know you could just let it create a brand new password resource, but then you have to clean up the old one after adopting a resource.

**Comment by manicminer** [comment]
I understand, but I'm not sure that would make for a user-friendly workflow, given that we currently allow non-destructive importing. Technically it wouldn't be the same resource anyway, since Terraform would have to recreate it and it would get a new ID, so I don't really see the value apart from that small convenience which I think falls outside of [general] expected behavior for Terraform.

**Comment by hbuckle** [comment]
Oh right, I was thinking of the previous behaviour where it could update the existing password resource with a new password value, but of course that isn't possible anymore.
