### ISSUE TITLE
azuread_application - block for all platform configurations.

### ISSUE THREAD

**Issue by JordanW94** [hashicorp/terraform-provider-azuread#469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've just recently started using the azuread_application resource and I'm in need of accessing Mobile and desktop applications platform configuration. It seems the web block is the only available platform for Terraform to configure.

### New or Affected Resource(s)

azuread_application

### Potential Terraform Configuration

```hcl
resource "azuread_application" "azuread" {
  display_name     = "namehere"
  owners = [object_id]
  sign_in_audience = "AzureADMyOrg"
  prevent_duplicate_names = true

  mobile_desktop_platform {
    redirect_uri = ["com.terraform.app://oauth", "http://localhost:300/"]
  }
}

```

Would this be possible?

### References
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application

* #0000

**Comment by manicminer** [comment]
Hi @JordanW94, thanks for the feature request. You are correct, at this time the provider can only configure some properties of the web block for application. This is due to API limitations, which we are currently working to move beyond by transitioning to a newer API (see #323 for details).

This work is ongoing at the moment and we hope to be able to release full support for different platform settings for applications in the near future.

**Comment by JordanW94** [comment]
Thanks for the quick reply @manicminer, I thought that would be case. I look forward to seeing the new features!
