### ISSUE TITLE
azuread_group detects "changes" to members incorrectly

### ISSUE THREAD

**Issue by roy-work** [hashicorp/terraform-provider-azuread#496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v0.15.5
on linux_amd64
```
&
`v1.6.0` of `azuread`

(Also, on TF Enterprise.)

### Affected Resource(s)

* `azuread_group`
* `azuread_group_membership`

### Terraform Configuration Files

```hcl
variable "foo_group_members" {
  type = list(string)
  default = [
    "alice@example.com",
    "bob@example.com",
    "chloe@example.com",
  ]
}

resource "azuread_group" "foo_group" {
  display_name = "foo-group"
}

data "azuread_user" "foo_group_members" {
  for_each = toset(var.foo_group_members)
  user_principal_name = each.key
}

resource "azuread_group_member" "foo_group_members" {
  for_each = data.azuread_user.foo_group_members
  group_object_id = azuread_group.foo_group.id
  member_object_id = each.value.id
}
```

### Expected Behavior

1. The TF is applied with `terraform apply`
2. Subsequent runs do not show changes, unless changes are made

### Actual Behavior

1. The TF was applied with `terraform apply`; that happened without error.
2. Subsequent runs show,
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # azuread_group.foo_group has been changed
  ~ resource "azuread_group" "foo_group" {
        id                      = "<uuid>"
      ~ members                 = [
          + "<uuid>",
          + "<uuid>",
          + "<uuid>",
        ]
        name                    = "foo-group"
        # (6 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
```

The UUIDs it lists are the UUIDs of the members of the group. They are all both members of the actual, current group in TF & the AAD. However, it seems like the diff here is listing them under `members = […]`, directly on the `azuread_group`, which they are _not_, so the diff makes "sense" in that regard, because `members` is not specified on the group directly.

However, membership is specified indirectly, as `azuread_group_membership` resources. Other providers have similar dual ways of specifying child resources like this: sometimes on the resource directly, sometimes as other resources, but my expectation is that the provider figures it out & only shows, as diffs, things that don't exist on one or the other.

### Steps to Reproduce

I'm actually not sure, since we have another `azuread_group` that doesn't show this behavior. However, that AD group was a `terraform import`, I think.

In the state file for the problematic group (`foo-group`, above), the state shows that `members` is empty:
```
    {
      "mode": "managed",
      "type": "azuread_group",
      "name": "foo_group",
      "provider": "provider[\"registry.terraform.io/hashicorp/azuread\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "description": "",
            "display_name": "foo-group",
            "id": "<uuid>",
            "mail_enabled": false,
            "members": [],
```

Our other, non-problematic Azure AD group _does_ have entries in the `members` group, but I suspect that might have been filled in during `import`.

**Comment by manicminer** [comment]
Hi @roy-work, thanks for reporting this.

This plan output is due to changes in Terraform Core and is intended to inform you when changes to potentially configurable properties are made. This happens because `members` is both an Optional property and a Computed attribute at the same time. If you don't specify the `members` property in your `azuread_group` resource, you will see this as part of your plan output but Terraform will not indicate any changes to be applied - following the output pasted in your report, you should also see:

```
No changes. Your infrastructure matches the configuration.
```

As mentioned, this is a behavior of Terraform Core and isn't something that can be changed by a provider, although in this case we likely wouldn't override this even if we could, since it's useful output and demonstrates that Terraform has detected the latest changes to your group (which you may be very interested to see if, for example, the group members are managed outside of Terraform). Accordingly, I'm going to close this issue because as mentioned it's not something the provider has any control over. Thanks!
