### ISSUE TITLE
Configure Desktop + devices in Azure AD using Terraform

### ISSUE THREAD

**Issue by raj13aug** [hashicorp/terraform-provider-azuread#509]
Hello Team,

I was not able to find the creation of (Desktop + devices) platform resource feature of terraform (azuread_application) also attached screen shot for the azure portal screen.

If it's possible please provide az command for (desktop + devices) creation.

Platform screen shot
![image](https://user-images.githubusercontent.com/5330003/128127973-79e8ed93-3bd2-4a3e-9886-25073edcd819.png)

There are multiple options is available. But How can I configured the (Desktop + devices) platform?

![image](https://user-images.githubusercontent.com/5330003/128127811-b5bd2b4a-bdc5-4144-8233-c74b6ca0a7e9.png)

**Terraform code** --> Doesn't support mobile app platform using web parameter

web {
    redirect_uris = ["https://login.microsoftonline.com/common/oauth2/nativeclient"]
    implicit_grant {
      access_token_issuance_enabled = True
    }
  }

Regards,
Nataraj.R

**Comment by manicminer** [comment]
Hi @raj13aug, thanks for requesting the ability to configure additional platforms for applications.

We have actually merged this functionality and it is due to be released in version 2.0 in the near future. Accordingly I'll mark this as resolved and link it to the v2.0 milestone, so you'll get notified in this issue once this has been released. Thanks!
