### ISSUE TITLE
datasource azuread_user is missing other_mails in the exported attributes

### ISSUE THREAD

**Issue by AmudaPalani** [hashicorp/terraform-provider-azuread#511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Hi @AmudaPalani, thanks for reporting this! We have actually added this missing attribute, amongst others, and it is due to released in v2.0 in the next few days.

Accordingly I'm going to close this issue as resolved, but I'll also mark it against the v2.0.0 milestone so you should get a notification when that's released.
