### ISSUE TITLE
Cannot destroy Azure AD groups when `prevent_duplicate_names` was specified

### ISSUE THREAD

**Issue by philthynz** [hashicorp/terraform-provider-azuread#531]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.0.1
+ provider registry.terraform.io/hashicorp/azurerm v2.74.0
```

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "azure" {
  display_name            = var.display_name
  owners                  = var.owners
  members                 = var.members
  security_enabled        = var.security_enabled ? true : false
  mail_enabled            = var.security_enabled ? false : true
  mail_nickname           = replace(lower(var.display_name), " ", "")
  types                   = var.security_enabled ? null : ["Unified"]
  prevent_duplicate_names = true
  lifecycle { ignore_changes = [members] }
}
```

### Debug Output

```
An existing "azuread_group" with name "Group-Name" (ID: "<ID>") was found and `prevent_duplicate_names` was specified. To be managed via Terraform, this resource needs to be imported into the State. Please see the resource documentation for "azuread_group" for more information.
```

### Panic Output

None

### Expected Behavior

Resource should be destroyed

### Actual Behavior

Resource cannot be destroyed

### Steps to Reproduce

terraform destroy

**Comment by manicminer** [comment]
Hi @philthynz, thanks for reporting this issue. I agree there are some rough edges around the `prevent_duplicate_names` functionality as this is only a best effort to help prevent duplicate group proliferation due to AAD allowing you to reuse group names. However, the error you described should not happen.

I have tried to reproduce this but in my testing I was able to apply/create a group and subsequently destroy it. Could you send a [debug log](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#logging-and-tracing)? This may help narrow down the cause of the error. Thanks!

**Comment by philthynz** [comment]
I purged my .terraform folder and re-downloaded the module I created. I can't re-create the error either. So I guess we're all good. Thanks!
