### ISSUE TITLE
Resource: azuread_application group_membership_claims stated as optional in docs not true

### ISSUE THREAD

**Issue by smark88** [hashicorp/terraform-provider-azuread#583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Versions:
```
terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "2.3.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.77.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.1.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "2.23.0"
    }
  }
  required_version = "0.14.11"
}
```

### Affected Resource(s)

* `azuread_application`
group_membership_claims is stated to be optional but errors when not set https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application#group_membership_claims

### Terraform Configuration Files

```hcl
resource "azuread_application" "main" {
  display_name            = "${var.name}-aks"
}

```

### Debug Output

```
2021-09-20T16:16:23.156-0400 [INFO]  plugin.terraform-provider-azuread_v2.3.0_x5: 2021/09/20 16:16:23 [DEBUG] Migrating `group_membership_claims` from v0 to v1 format: timestamp=2021-09-20T16:16:23.156-0400
      - .group_membership_claims: planned set element cty.StringVal("") does not correlate with any element in actual
```

### Expected Behavior

Run plan no change

### Actual Behavior

`Error: .group_membership_claims: missing expected [`

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by manicminer** [comment]
Hi @smark88, thanks for raising this issue. I believe the error you are seeing is related to the state upgrade between pre-v2 and v2.x. There is a known issue with the azuread_application data source where, due to internal Terraform limitations, it's not possible to upgrade to v2.x without manual intervention. If you have any azuread_application _data sources_ in your configuration, you will need to do one of the following prior to upgrading:

- Run `terraform state rm data.azuread_application.example` to remove the data source(s) from your statefile
- Comment out the data source(s) in your configuration, upgrade the provider version, run `terraform refresh`, and uncomment the data source(s)
- Manually edit your state file to change the attribute `"group_membership_claims": ""` to `"group_membership_claims": []` (not recommended unless you are confident and the other two options are infeasible)

If you are using this data source, please give one of these a try and this should work around the error.
If you don't use this data source, and consequently the error relates to an azuread_application _resource_, please post the relevant part of your configuration and I'll be happy to investigate further. Thanks!

**Comment by smark88** [comment]
removing the data sources from the state appears to work.

**Comment by manicminer** [comment]
Thanks for the feedback! We'll add a note to the migration guide about this.
