### ISSUE TITLE
What are the least privileges Azure AD built-in roles needed to create azuread_service_principal resource?

### ISSUE THREAD

**Issue by sheeeng** [hashicorp/terraform-provider-azuread#605]
What are the least privileges [Azure AD built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#application-developer) needed to create [azuread_service_principal](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/service_principal) resource?

For example, [Application Developer](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#application-developer) has following actions granted.

| Actions                                                  | Description                                                                 |
| -------------------------------------------------------- | --------------------------------------------------------------------------- |
| `microsoft.directory/applications/createAsOwner`           | Create all types of applications, and creator is added as the first owner \ |
| `microsoft.directory/oAuth2PermissionGrants/createAsOwner` | Create OAuth 2.0 permission grants, with creator as the first owner         |
| `microsoft.directory/servicePrincipals/createAsOwner`      | Create service principals, with creator as the first owner                  |

We would like to restrict these privileges and only permit least privileges Azure AD built-in roles in order to create service principles.

**Comment by manicminer** [comment]
Hi @sheeeng, the permissions vary depending on what you want users to be able to to do with a service principal. By default, non-guest users can create service principals and modify some properties of SPs that they own. [These official docs](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/users-default-permissions) are a good resource but you'd have to experiment with Terraform to see how this translates to properties in the azuread_service_principal resource - particularly since the API does not always correlate with the docs and can even vary per tenant. There is a history of inconsistent application of permissions by the API - see #529, #535, #538, #544, #546, #561 and #581 for context.

This complexity is why [we indicate Application Administrator](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal#api-permissions) as the best role to assign for full functionality, though I understand you are probably trying to avoid that. I'd suggest starting with no directory role assigned (i.e. using the default permissions) whilst ensuring that the calling user is specified in the `owners` property for *both the application and service principal*, and working your way up via experimentation from there.

**Comment by sheeeng** [comment]
Hi Tom, thank you for the clarification. I will close this issue at this moment.
