### ISSUE TITLE
Cloud Shell doesn't allow running the TF Azure AD 2.x code due to MSI error

### ISSUE THREAD

**Issue by marcosgm** [hashicorp/terraform-provider-azuread#633]
see https://github.com/Azure/CloudShell/issues/112

```
╷
│ Error: could not configure MSI Authorizer: NewMsiConfig: could not validate MSI endpoint: received HTTP status 404
│
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on main.tf line 1, in provider "azuread":
│    1: provider "azuread" {
│
```

**Comment by edyoung** [comment]
@manicminer let us know if you think this is due to an error in Cloud Shell. I can reproduce the issue but I'm not clear what the problem is.

**Comment by marcosgm** [comment]
I went ahead and tested the Go library (Hamilton) and filed a bug as they don't support the MSI endpoints inside cloudshell https://github.com/manicminer/hamilton/issues/116

**Comment by manicminer** [comment]
@edyoung Thanks for reaching out - this isn't strictly due to an error in Cloud Shell, rather it's arisen from an assumptoin that MSI endpoints respond similar in various environments. There is a sanity check at configuration time that tries to get a 200 response from the metadata service, but either there isn't such a service in Cloud Shell or the URL is different. It's not a huge problem, the sanity check adds minimal value and I believe we can remove it.
