### ISSUE TITLE
Azure AD app secret rotation

### ISSUE THREAD

**Issue by Uvindu96** [hashicorp/terraform-provider-azuread#671]
I have several azure AD apps and and their secret expiring dates are getting closes, So there is a requirement to rotate the AD app secrets, I have implemented a pipeline to rotate the secretes, but the problem is since AD apps are configured using terraform, after I rotate the secrets, next time when I apply terraform it will give me a diff in password object that I currently have for my AD apps. Currently I'm not using a secret vault to store the AD app credentials.
```
resource "azuread_service_principal_password" "service_principal_password" {
  service_principal_id = var.sp_internal_id
  description          = var.password_description
  value                = random_password.password.result
  end_date             = var.password_end_date
}

```

```
module "cd-project-azurerm-test-storage-account-service-connection" {
  source                = "git::https://github.com/wso2-enterprise/azure-terraform-modules.git//modules/azuredevops/ARM-Service-Endpoint?ref=v2.0.0"
  project_id            = module.cd-project.project_id
  project               = var.project
  service_endpoint_name = var.devops_cd_project_azurerm_test_storage_account_service_endpoint_name
  subscription_id       = var.subscription_id
  subscription_name     = var.subscription_name
  tenant_id             = var.tenant_id
  description           = var.devops_cd_project_azurerm_test_storage_account_service_endpoint_description
  service_principal_id  = module.test-storage-account-dev-ops-ad-sp.sp_app_id
  service_principal_key = module.test-storage-account-dev-ops-ad-sp-password.sp_password
  depends_on = [
    module.cd-project,
    module.test-storage-account-dev-ops-ad-sp-password,
    module.test-storage-account-dev-ops-ad-sp,
    module.test-storage-account-dev-ops-ad-sp-rbac
  ]
}
```

Is there any solution to avoid this diff after the secret rotation ?

**Comment by manicminer** [comment]
Hi @Uvindu96, thanks for opening this issue.

It looks like you may be using an older 0.x or 1.x provider version - whilst I'm not sure of the behavior with 0.x releases, with a recent 1.x version you should be able to provide a new value for `value` and Terraform will rotate the password.

In v2.0, the `value` property for `azuread_application_password` was removed due to API constraints, and I would recommend upgrading to the latest version if you are able to. With the latest 2.x release, a `rotate_when_changed` property was added to enable rotation based on criteria for your particular use case.

For all versions, you might want to use the [`create_before_destroy` lifecycle meta-property](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#create_before_destroy) to control how Terraform orchestrates the rotation.

If you rotate the password outside of Terraform, it will not recognize it because the resource ID will be different - in such a case you'd have to import the secret that you rotated out of band. The [resource documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_password) has an example for this, showing the necessary resource ID format.

I hope this helps. Since this is more of a usage question, and because we use GitHub issues for tracking feature requests and bugs in the provider, I'm going to close this issue for now so that we can maintain focus on that. We instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html) or in our community Slack workspace. Thanks!

**Comment by Uvindu96** [comment]
Hi @manicminer ,

I just checking this again, I have created the configurations as you mentioned, I just want to when we add the attribute `rotate_when_changed` it will create a new password resource according to the timestamp we set right ? and I want to know that this is a feature that Terraform only provides or this is a feature from Azure AD ? since Azure AD does not provide the key rotation feature, I'm wondering how Terraform is achieving this rotation ? I really appreciate your answer for this, thanks in advance :)

**Comment by manicminer** [comment]
@Uvindu96 As per the documentation, `rotate_when_changed` will trigger reprovisioning (hence rotation) of the password when any of its keys or values change

**Comment by Uvindu96** [comment]
@manicminer Thanks for the clarification, one last thing I want to know, This is a Terraform feature right ? Because there is no rotation feature provided in azure.

**Comment by manicminer** [comment]
@Uvindu96 Correct, the net result is rotation but that's just a useful way of saying that Terraform removes and recreates the password
