### ISSUE TITLE
azuread_group "objects changed outside of Terraform" message after apply

### ISSUE THREAD

**Issue by jimsheldon** [hashicorp/terraform-provider-azuread#688]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
$ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.87.0
```

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "example" {
  behaviors               = []
  display_name            = "example"
  description             = "example description"
  members                 = ["1e361e71-ee38-4857-87f4-de58306abcdef"]
  prevent_duplicate_names = true
  provisioning_options    = []
  security_enabled        = true
  types                   = []
}
```

### Expected Behavior

After applying this resource, I do not expect to see a "Objects have changed outside of Terraform" message for this resource when running `terraform plan`.

### Actual Behavior

The following plan output is seen:
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azuread_group.example has been changed
  ~ resource "azuread_group" "all" {
      + behaviors               = []
        id                      = "1e361e71-ee38-4857-87f4-de58306abcdef"
      + provisioning_options    = []
      + types                   = []
        # (12 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following
plan may include actions to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.
```

### Steps to Reproduce

Apply the provided `azuread_group` resource example above, then run `terraform plan`.

1. `terraform apply`

### Important Factoids

None that I know of...

**Comment by manicminer** [comment]
Hi @jimsheldon, thanks for reporting this. The output you are seeing is due to changes in Terraform Core that were included in the [Terraform v0.15.4 release](https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md#0154-may-19-2021). I appreciate that in this case, such output isn't helpful since the resource was literally just created by Terraform and the diff being surfaced here consists of zero values. Unfortunately, in order to maintain SDK compatibility with earlier versions of Terraform, this means in some cases, included here, we're unable to subdue this message or otherwise mitigate it.

There is an upstream issue https://github.com/hashicorp/terraform/issues/28803 which I'd recommend subscribing to as this may be updated in the longer term, however it does look like this feature is here to stay for the time being. Accordingly, I'm going to close out this issue in favor of the linked upstream issue.
