### ISSUE TITLE
service_principal permissions Directory.ReadWrite.All

### ISSUE THREAD

**Issue by craigbryson** [hashicorp/terraform-provider-azuread#717]
Hi!

We are trying to use a service principal to provision other service principals using the provider and according to the docs:

> When authenticated with a service principal, this resource requires one of the following application roles: Application.ReadWrite.All or Directory.ReadWrite.All

Could someone explain why the permissions need to be so broad? We are a little constrained by our governance, but we are able to use `az ad sp create` as objects without the above permissions and it works ok

**Comment by manicminer** [comment]
Hi Craig, thanks for opening this issue. This is more of a usage question but I'll try to explain.

At this time I don't believe az-cli is using the same API as we are using in the Terraform provider. We generally base our indicated permissions off of the [API documentation for the endpoints that we're using](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-beta&tabs=http), although we do try to validate these with testing as they are not always entirely accurate. Unfortunately we don't have any control over the behavior of the API with regards to permissions.

This is only one aspect however, since Terraform manages the entire lifecycle of a resource including it's creation, any updates during it's lifetime and finally it's destruction, which involves multiple different operations with discreet required permissions. Additionally, permissions differ depending on whether you're authenticated as a service or a user principal, whether you are a guest principal in the tenant you're managing, your tenant security settings, and several other factors.

We have observed that many people can create service principals whilst authenticated as another service principal, provided that the calling principal is an owner of both the linked application registration and the service principal being created. As such, depending entirely on the context, you may find that you can create and/or update and/or delete service principals with lesser permissions than those we document.

If you're authenticating as a user principal (e.g. via the azure CLI), I recommend consulting [this doc](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/users-default-permissions) for more info on default tenant permissions for users.

As mentioned before, this is more of a usage question, as we feel we currently have the best balance of documented permissions for the most straightforward scenarios - for larger or more complex deployments we recommend your own testing/investigation. It's not practical for us to expand our documentation further as this is a moving target and ultimately the responsibility of Azure to document. As such I'm going to close this issue for now, and recommend that you contact Azure support if you need further clarification. Thanks :)

**Comment by craigbryson** [comment]
Thank you @manicminer that helps! I'll have a play around with permissions and see if I can make something fit
