### ISSUE TITLE
Issue azuread provider 2.15 - "URI must have a trailing slash when there is no path segment"

### ISSUE THREAD

**Issue by skeletonrush** [hashicorp/terraform-provider-azuread#718]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

```hcl
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
```
### Terraform Configuration Files

```hcl
resource "azuread_application" "appreg" {
  display_name                   = "myapp"
  identifier_uris                = ["https://${local.default_aad_domain}/${local.default_as_domain}"]
  fallback_public_client_enabled = false
  prevent_duplicate_names        = true
  owners                         = ["3exxxxxxxxx"]
  web {
    redirect_uris = [
      "https://${local.default_as_domain}",
      "https://${local.default_as_domain}/.auth/login/aad/callback",
      "https://${local.default_as_domain}/auth.html"
    ]
  }
}
```

### Expected Behavior

App Registration on AAD should be successfully created when the redirect_uris of the "web" section have no trailing "slash", because:

1. such url "https://xxx/.auth/login/add/callback" is accepted by the Azure UI
2. when adding a trailing slash to the redirect_uris, the resource is created but the oidc login process fails because Azure App Service uses the following redirect_uri: "https://xxx/.auth/login/add/callback" (without trailing slash) and no match can be found with the configuration of the "app registration" in AAD.

### Actual Behavior

Terraform plan fails with the following error:
```hcl
╷
│ Error: URI must have a trailing slash when there is no path segment
│
│ with module.xxx[0].azuread_application.appreg,
│ on ../module/main.tf line 60, in resource "azuread_application" "appreg":
│ 60: redirect_uris = [
│ 61: "https://${local.default_as_domain}",
│ 62: "https://${local.default_as_domain}/.auth/login/aad/callback",
│ 63: "https://${local.default_as_domain}/auth.html"
│ 64: ]
│
╵
```
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

* https://github.com/hashicorp/terraform-provider-azuread/issues/642

**Comment by manicminer** [comment]
Hi @skeletonrush, thanks for raising this issue. The validation rules for redirect URIs in the provider are based off [Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url) and the behavior that we observe with the API that we use.

As per the above docs, redirect URIs with no path segment are returned by the API with a trailing slash. In order to maintain state consistency in Terraform, this forces us to require that the trailing slash is included in the configuration for an application. Note this only applies to URIs without a path segment, such as the first URI `https://${local.default_as_domain}` in your config example. It does not apply when any path is appended, for example with `https://xxx/.auth/login/add/callback`.

I believe if you include a trailing slash in the first URI in your example config, the validation will pass accordingly. Can you give this a try and let us know if this resolves the error? Thanks!

**Comment by skeletonrush** [comment]
Hi @manicminer , yes you're right, it only applies for a single URI. Sorry, I thought it was also for the "callback" URI. Now, with "https://${local.default_as_domain}/" the deployment is ok and the oidc login process works well.
