### ISSUE TITLE
Resource: azuread_service_principal Tags does not allow multiple values:

### ISSUE THREAD

**Issue by Lucero7919** [hashicorp/terraform-provider-azuread#726]
**### Terraform (and AzureAD Provider) Version**
TF v1.1.4 and AzureAD v2.16.0

**### Affected Resource(s)**
azuread_service_principal

**### Terraform Configuration Files**
```
resource "azuread_service_principal" "aad_sp" {
  application_id = "2565bd9d-da50-47d4-8b85-4c97f669dc36"
  tags = merge({ capability = module.globals_tags.identity_management, description = "AAD DS Service Principal" }, module.globals_tags.core_common_tags)

  #tags           = ["Azure AD Service Principal"]
}
```

**### Expected Behaviour**

The tags value should adopt the merged values of capability (from module), description and core_common_tags (from module). On any other resource, this would appear as:
```

      + tags                = {
          + "capability"  = "Azure AD DS"
          + "createdBy"   = "Terraform"
          + "description" = "AAD DS Service Principal"
          + "domain"      = "core tag"
          + "system"      = "core tag"
        }
```

**### Actual Behaviour**

TF Plan fails with:
```
Error: Incorrect attribute value type
│
│   on aad.tf line 5, in resource "azuread_service_principal" "aad_sp":
│    5:   tags = merge({ capability = module.globals_tags.identity_management, description = "AAD DS Service Principal" }, module.globals_tags.core_common_tags)
│     ├────────────────
│     │ module.globals_tags.core_common_tags is object with 3 attributes
│     │ module.globals_tags.identity_management is "Azure AD DS"
│
│ Inappropriate value for attribute "tags": set of string required.
```
Commented out "tags" in example above, with single instance (  tags           = ["Azure AD Service Principal"]) works.

### Steps to Reproduce

1. Create AD Service Principal resource with merged tags
2. terraform init
3. terraform plan

**Comment by Lucero7919** [comment]
Upon further investigation, I've noticed that the tag block for the resource outputs tags [ ] whereas every other resource outputs tags as {}

Example:
Any other resource:
```
      + tags                = {
          + "capability"  = "Azure AD DS"
          + "createdBy"   = "Terraform"
          + "description" = "AAD DS Service Principal"
          + "domain"      = "core tag"
          + "system"      = "core tag"
        }
```
note curly brackets.

And the output tags for the azuread_service_principal
```
      + tags                        = [
          + "AAD DS Service Principal",
        ]

```
note the square brackets

**Comment by manicminer** [comment]
Hi @Lucero7919, thanks for raising this issue. Whilst most Azure resources provide tags as a store for user metadata, in Azure AD, applications and service principals are different. For these resources, tags are lists of special magic values that affect the behavior of the resource in question. For more information on this, please see the [documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal#argument-reference) on the `feature_tags` property.

Since this is more of a feature request for Azure, I'm going to close this one for now and would recommend that you open a support ticket with Azure if you need to communicate with them on this feature. Thanks!
