### ISSUE TITLE
Error: Could not create app role assignment

### ISSUE THREAD

**Issue by dbrewerExperlogix** [hashicorp/terraform-provider-azuread#736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform v 1.15 (Latest) and Azure AD Provider version 2.18.0 (Latest)

### Affected Resource(s)

azuread_app_role_assignment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

resource "azuread_app_role_assignment" "assignment"{
  app_role_id = "00000000-0000-0000-0000-000000000000"
  principal_object_id = <objectId of user or group>
  resource_object_id = <objectid of service principal>
}

### Expected Behavior

a role assignment for the user or group, with the role of "Default Access" should have been created.

### Actual Behavior

Received the output below:

 AppRoleAssignedToClient.BaseClient.Post():    
│ unexpected status 400 with OData error:       
│ Request_BadRequest: Permission being assigned 
│ was not found on application

### Steps to Reproduce

Create a azuread_app_role_assignment resource with the app_role_id set to "00000000-0000-0000-0000-000000000000".

1. `terraform apply`

### References

The Azure PowerShell module directs to use 00000000-0000-0000-0000-000000000000
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadserviceapproleassignment?view=azureadps-2.0

* #0000

**Comment by manicminer** [comment]
Hi @dbrewerExperlogix, thanks for raising this. Reading the docs for the [New-AzureADServiceAppRoleAssignment cmdlet](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadserviceapproleassignment?view=azureadps-2.0) and the corresponding [appRoleAssignment API endpoint](https://docs.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0) (which we use in the provider), indicates that you can only specify a zeroed UUID for the app role ID, when the application does not define any app roles. I've tested this and such a scenario works just fine with the provider. However, if the application defines any roles, you get the aforementioned 400 response which I would say corresponds with the docs:

> This app role must be exposed in the appRoles property on the resource application's service principal (resourceId). If the resource application has not declared any app roles, a default app role ID of 00000000-0000-0000-0000-000000000000 can be specified to signal that the principal is assigned to the resource app without any specific app roles.

Since this seems to be working as expected, I don't believe there's anything for us to do here and accordingly I'm going to close this one for now. Thanks!
