### ISSUE TITLE
Using the Provider with an SP provided by Vault's Azure Secrets Engine

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/terraform-provider-azuread#738]
I have googled around for something that answers this and haven't found the detail I'm looking for.

We want to use the AzureAD Provider to perform AAD Group and User adds/deletes/changes.

We have a Vault instance with the Azure Secrets Engine up and running. The engine has roles defined for various Azure Subscriptions and Azure Roles. We are able to use our TFE instance, with Vault, to manage infrastructure in Azure. 👍

Now I am prototyping some Terraform that will allow us to do some AAD Group and User configs.
Im struggling to determine what the Vault Role configuration I need is. Since Vault will provide an SP, how do I tell Vault to configure that SP so it can be used with the Azure AD Provider?

Maybe im missing something here and it's just cause its late. IDK.
I looked around for some Hashicorp Doco in Vault and the Azure AD Provider for this pattern. Didn't come up with anything. That surprised me tbh.

Can I buy a cluepon please?

**Comment by manicminer** [comment]
Hi @ausfestivus, thanks for opening this issue. As this question is about the Vault Azure secrets engine, I'd suggest opening an issue on the [repository for that project](https://github.com/hashicorp/vault-plugin-secrets-azure) instead. Whilst I am not completely familiar with that project, looking at the docs I'd say you perhaps have two options:

1. Assign a directory role to a group and [ensure group membership using Vault](https://www.vaultproject.io/docs/secrets/azure#azure-groups). The ability to assign roles to groups is an AAD Premium feature though.
2. Supply a pre-existing service principal to the Azure secrets engine that you have preconfigured with the necessary API or directory roles (perhaps using Terraform!)

I hope this helps. As mentioned, since this relates to the Vault plugin rather than the Terraform provider, I'm going to close this issue for now whilst suggesting perhaps opening an issue on the vault-plugin-secrets-azure repo, or alternatively check out [our community resources](https://www.hashicorp.com/community).
