### ISSUE TITLE
allowPublicClient property of azure ad application Manifest is set to false but should be null

### ISSUE THREAD

**Issue by logcorner** [hashicorp/terraform-provider-azuread#773]
when using the terraform configuation below

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.0.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.20.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.1.0"
    }
  }
}
provider "azurerm" {
  features {}
}

provider "azuread" {
  client_id     = var.client_id
  client_secret = var.client_secret
  tenant_id     = var.tenant_id
}
```

```
resource "azuread_application" "front_end_spa_application" {
  
  }
```

The azuread application will be created with "allowPublicClient": false  and the result is that the front end spa configured with this application will not work and I have to update  "allowPublicClient" property of the manifest to null ("allowPublicClient" :null) to fix it

**Comment by manicminer** [comment]
hi @logcorner, thanks for opening this issue. I believe you'll need to set the `fallback_public_client_enabled` property of the application as this setting is not enabled by default. This corresponds to the `allowPublicClient` property in the app manifest. Can you give this a try and let us know if this resolves the issue with your SPA?

**Comment by logcorner** [comment]
hI @manicminer does not work 
in the terraform file I have added the following : fallback_public_client_enabled = null
![MANIFEST](https://user-images.githubusercontent.com/5066547/164024122-2bbcd91c-b5d7-499f-91ef-7b749f7e11c9.png)
![TERRAFORM](https://user-images.githubusercontent.com/5066547/164024126-c3003204-c749-42bc-b536-b07e61441563.png)

**Comment by manicminer** [comment]
@logcorner Sorry I should have been more specific - that property doesn't support `null` as a value, in fact that's Terraform's way of omitting the property from the provider. Can you try setting it to `true`?

**Comment by logcorner** [comment]
@manicminer *
the allowPublicClient  property should be null in the manifest file.  if it is equal to  false ,the azure ad authentication using the app registration will fail.
And because it is not a public client I think it should not be equal to true.
I will try setting it to true and come back to you
Regards

**Comment by logcorner** [comment]
Hi @manicminer it works when I use fallback_public_client_enabled = true

**Comment by theoboardpro** [comment]
Just adding to this issue, we are using PKCE, and we require the value to be null. Setting to true does not work as we do not use grant flows.

When looking at the manifest it should be 
![image](https://user-images.githubusercontent.com/95889728/188822738-9b1fad16-03fa-416d-93dd-8068fe8a73e0.png)

However, setting to false sets the value to false, and the flow breaks on the WebApp.

Is this something that can be supported? Since it is causing is to do a manual step in our terraform process to update.

**Comment by sberube** [comment]
Any progress on this? We are facing the same issue on our side too :(

**Comment by manicminer** [comment]
Unfortunately this will require a breaking change, as there isn't a safe way for us to handle a third value for boolean fields. We'll be able to address this in the version 3.0 of the provider.

**Comment by manicminer** [comment]
@Masahigo As per my preceding comment, this requires a breaking change to fix and so will be addressed in the next major version of the provider.

**Comment by manicminer** [comment]
Thanks again for reporting this issue, and for the discussion around use cases. As mentioned previously, resolving this in the existing `azuread_application` resource requires a breaking change to the provider. In order to open up more configuration scenarios for practitioners, we're releasing a new set of resources for application management. These are being built to enable more fine grained control of properties like `allowPublicClient` / `fallbackPublicClientEnabled`, and should resolve this issue. Accordingly, I've linked this issue to #1214.

Our recommendation will be to consider adopting the soon-to-be-introduced `azuread_application_registration` resource. This will preserve the default `null` value for this property, whilst also enabling it to be explicitly set (to either `true` or `false`), with use of the `azuread_application_fallback_public_client` resource.
