### ISSUE TITLE
output "client_secret_value" is not printing

### ISSUE THREAD

**Issue by gouthamkamre68** [hashicorp/terraform-provider-azuread#845]
Hi,

i'm creating client secret using terraform "Resource: azuread_application_password" but unable to get secrets value in terraform output

output "client_secret_value" {
  description = "Password for service principal."
  value       = azuread_application_password.main.value
  sensitive   = true
}

output value:- client_secret_value = <sensitive>

Please help me to get it.

**Comment by Threpio** [comment]
Hi There @gouthamkamre68 

If you mark an output as `sensitive = true` then it will not print it to stdout when running terraform plan/apply.

https://www.terraform.io/language/values/outputs#sensitive-suppressing-values-in-cli-output

**Comment by gouthamkamre68** [comment]
if i  remove sensitive it's throwing error as Output refers to sensitive values.

output "client_secret_value" {
description = "Password for service principal."
value = azuread_application_password.main.value
}

Error: Output refers to sensitive values
│
│   on output.tf line 21:
│   21: output "client_secret_value" {
│
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root      
│ module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.
│
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
![output](https://user-images.githubusercontent.com/37205255/179521949-62643290-9852-4c59-9d77-522ad646ed12.JPG)

**Comment by Threpio** [comment]
Understood - Apologies for misunderstanding the situation.

If you get that it redacts it due to it being sensitive like: `client_secret_value = <sensitive>` then this is intentional and is a terraform decision not the providers.

You can use the `terraform output client_secret_value` command to print it out after you have run the plan.

In the past when I have created secrets I have created a secret in a keyvault and saved it there so they can be accessed by myself/team or application.

**Comment by Threpio** [comment]
@manicminer - This can be closed
