### ISSUE TITLE
New Property on azuread_application

### ISSUE THREAD

**Issue by rohrerb** [hashicorp/terraform-provider-azuread#886]
Request to add `Assignment Required` to `azuread_application`.

Image of the field in Azure AD:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/15711466/190233518-b99a44bc-abb5-4601-a566-e8d44049cb59.png">

**Comment by naitmare01** [comment]
That is possible today if using the correct resource, [azuread_service_principal](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal) and the attribute `app_role_assignment_required`.

The [azuread_application](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application) is the app registration and doesn't have that settings because it is two different things in Azure AD.

**Comment by manicminer** [comment]
Thanks @naitmare01, closing this as already implemented.
