### ISSUE TITLE
identifierUris and resourceAppId in requiredResourceAccess iuuse with creating along with application

### ISSUE THREAD

**Issue by Hakeem3242** [hashicorp/terraform-provider-azuread#905]
identifi url update with app id 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
identifierUris and resourceAppId in requiredResourceAccess iuuse with creating along with application.
When we are trying to create application manullay Identifieruri and resource app id for api permissions getiing created with app id by default and when we run terraform scripts app idis are known after apply.
As per terraform document **https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application* uuid's are updated and  having error uuid's which are listed below

![image](https://user-images.githubusercontent.com/87963051/195012324-1986c5d5-7d8f-4374-b703-37f8a9e40518.png)

X This application object has been removed from the directory or is not available.

how can i resouve this issue , how to update required resource acess and identifineruris with app registation ?
 here iam sharing the code.

data "azuread_client_config" "current" {}

resource "azuread_application" "example" {
  display_name     = "example"
  identifier_uris  = ["api://example-app"]
  owners           = [data.azuread_client_config.current.object_id]
  sign_in_audience = "AzureADMultipleOrgs"

  api {
    mapped_claims_enabled          = true
    requested_access_token_version = 2

    known_client_applications = [
      azuread_application.known1.application_id,
      azuread_application.known2.application_id,
    ]

    oauth2_permission_scope {
      admin_consent_description  = "Allow the application to access example on behalf of the signed-in user."
      admin_consent_display_name = "Access example"
      enabled                    = true
      id                         = "96183846-204b-4b43-82e1-5d2222eb4b9b"
      type                       = "User"
      user_consent_description   = "Allow the application to access example on your behalf."
      user_consent_display_name  = "Access example"
      value                      = "user_impersonation"
    }

    oauth2_permission_scope {
      admin_consent_description  = "Administer the example application"
      admin_consent_display_name = "Administer"
      enabled                    = true
      id                         = "be98fa3e-ab5b-4b11-83d9-04ba2b7946bc"
      type                       = "Admin"
      value                      = "administer"
    }
  }

  app_role {
    allowed_member_types = ["User", "Application"]
    description          = "Admins can manage roles and perform all task actions"
    display_name         = "Admin"
    enabled              = true
    id                   = "1b19509b-32b1-4e9f-b71d-4992aa991967"
    value                = "admin"
  }

  app_role {
    allowed_member_types = ["User"]
    description          = "ReadOnly roles have limited query access"
    display_name         = "ReadOnly"
    enabled              = true
    id                   = "497406e4-012a-4267-bf18-45a1cb148a01"
    value                = "User"
  }

  feature_tags {
    enterprise = true
    gallery    = true
  }

  optional_claims {
    access_token {
      name = "myclaim"
    }

    access_token {
      name = "otherclaim"
    }

    id_token {
      name                  = "userclaim"
      source                = "user"
      essential             = true
      additional_properties = ["emit_as_roles"]
    }

    saml2_token {
      name = "samlexample"
    }
  }

  required_resource_access {
    resource_app_id = "00000003-0000-0000-c000-000000000000" # Microsoft Graph

    resource_access {
      id   = "df021288-bdef-4463-88db-98f22de89214" # User.Read.All
      type = "Role"
    }

    resource_access {
      id   = "b4e74841-8e56-480b-be8b-910348b18b4c" # User.ReadWrite
      type = "Scope"
    }
  }

  required_resource_access {
    resource_app_id = "Xxx-xxxxxxxxx-xxxxxxxxxxx" # for application acess 

    resource_access {
      id   = "594c1fb6-4f81-4475-ae41-0c394909246c" # ActivityFeed.Read
      type = "Role"
    }
  }

  web {
    homepage_url  = "https://app.example.net"
    logout_url    = "https://app.example.net/logout"
    redirect_uris = ["https://app.example.net/account"]

    implicit_grant {
      access_token_issuance_enabled = true
      id_token_issuance_enabled     = true
    }
  }
}
 

### New or Affected Resource(s)

* azuread_XXXXX

### References

"https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application"

**Comment by manicminer** [comment]
Hi @Hakeem3242, thanks for reporting this difficulty. If I understand correctly, it seems like you'd like to include the client ID (application ID) as part of the identifier URI(s) and/or API permissions (required resource access), but you're unable to do this without causing a circular reference in your configuration.

Until recently, this scenario was difficult for us to support using a single resource. To achieve this, we recently [added some new resources](https://github.com/hashicorp/terraform-provider-azuread/pull/1214) for managing applications. Specifically for your use case, I believe you'd be interested in the [azuread_application_registration](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_registration), [azuread_application_identifier_uri](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_identifier_uri), and [azuread_application_api_access](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_api_access) resources. We do not yet have a standalone resource for optional claims, but this should be added in this week's provider release.

Accordingly, since I believe these new resources will resolve your issue, I'm going to close this one as resolved in v2.44 of the provider. Please upgrade to the latest version (v2.44.1 at time of writing) in order to utilize these new resources. Thanks!
