### ISSUE TITLE
Suggestion: azuread_application: make `required_resource_access -> resource_access` non-position-dependent

### ISSUE THREAD

**Issue by SeanKilleen** [hashicorp/terraform-provider-azuread#919]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am reconciling some Terraform with existing environments.

An `azuread_application` resource has a `required_resource_access` block with `resource_access` blocks within it.

In the dev environment, those access blocks are in order A, B, C, D
In the QA environment, those access blocks are in order B, A, C, D

They are effectively/functionally the same, but Terraform sees them as different, and wants to drop them and recreate them. 

That's fine. But since there's no effective difference, it might be nice to respect that in order to avoid an unnecessary change being made.

### New or Affected Resource(s)

* azuread_application

**Comment by manicminer** [comment]
@SeanKilleen Thanks for the suggestion. The ordering here, and in particular Terraform's insistence on it, is due to the internal schema of this property within the provider. It may be possible to change this, however due to Terraform's design this would be a breaking change and would make it no longer possible to reference this property reliably from another resource.

**Comment by SeanKilleen** [comment]
I see; thank you for clarifying!  Not opposed to closing this if the ROI for a breaking change isn't worth it; the human eye can see it's the same in a plan with a little squinting. :)

**Comment by napramirez** [comment]
Will it perhaps help if the `required_resource_access` blocks are converted to a list instead? After all, when it translates to the Azure manifest, it is a list.

**Comment by thackman7** [comment]
I'm having this exact same issue across environments as I'm porting our manually created applications into Terraform. 
I can understand that they are out of order due to manual portal changes. But, once they are terraformed, will the order stay A,B,C,D or will the required_resource_access blocks randomly change order at the whim of graph api? Are these differences an ongoing fact of life or just a one time issue?

**Comment by SeanKilleen** [comment]
@thackman7 in our experience, once written by Terraform (or reconciled to be in the order TF expects), they will stay in the expected position. We haven't had any revert on us or cause issues again.

**Comment by manicminer** [comment]
As mentioned, we won't be able to make this change until the next major release of the provider - and it's not yet clear whether we'll do this as it will break configurations that consume this attribute as a list. However, in the next release we're adding the `azuread_application_api_access` resource, which is a decoupled `required_resource_access` from `azuread_application` which uses a TypeSet to represent the `permissions` (aka `resource_access`), in addition to an `azuread_application_registration` and other narrowly-scoped resources for improved composability in configurations.
