### ISSUE TITLE
Not able to read existing Azuread users and add them in the azuread_group_member by having "directory.readwrite.all" api-permission to principal

### ISSUE THREAD

**Issue by RaghavK12RK** [hashicorp/terraform-provider-azuread#923]
I have authenticated with Azuread provider with the required `tenant_id`, `client_secret_key` & `client_id` i could able to authenticate with the azuread provider.

When running `terragrunt plan` i could not able to read the existing list of users by using data "azuread_users" resource.

Following below is the error i am facing
![image](https://user-images.githubusercontent.com/109405973/199976527-ddc74824-de77-480b-ad9a-de95ccf929a8.png)

issue of error in text format

Error: Finding user with UPN: "example@test.com"
│
│   with data.azuread_users.test_users["example@test.com"],
│   on main.tf line 56, in data "azuread_users" "test_users":
│   56: data "azuread_users" "test_users" {
│
│ UsersClient.BaseClient.Get(): unexpected status 403 with OData error:
│ Authorization_RequestDenied: Insufficient privileges to complete the
│ operation.

Please help me in resolve this issue, Required support or inputs needed, Thank you!

**Comment by garysinot** [comment]
I am having the same issue as well.  
Not able to read or write.

**Comment by RaghavK12RK** [comment]
Can we have this issue resolved and resolve this

**Comment by RaghavK12RK** [comment]
> I am having the same issue as well. Not able to read or write.

Hi, Do you have directory.readwrite.all permission for api?

**Comment by manicminer** [comment]
Hi, thanks for raising this issue. This is more of a usage question and I would recommend double checking your effective permissions, ensuring that the necessary API role(s) are assigned to your principal (app role assignment aka admin consent). The provider makes no assumptions about your directory permissions, nor does it have any control over permissions.

Since we use GitHub issues for tracking bugs and feature requests, I'm going to close this for now. However I would suggest joining our community Slack group where you'll be able to get help from other practitioners - the invite link is in the project readme.
