### ISSUE TITLE
"azuread_group" creation fails if "mail_nickname" contains "." (dot) character

### ISSUE THREAD

**Issue by ju-la-berger** [hashicorp/terraform-provider-azuread#932]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.30.0
```

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "foo_bar" {
  description              = "foo bar"
  display_name             = "foo.bar"
  external_senders_allowed = true
  mail_enabled             = true
  mail_nickname            = "foo.bar"
  types                    = ["Unified"]
  visibility               = "Private"
}
```

### Debug Output

```
$ terraform apply
╷
│ Error: Value cannot contain these characters: @()\[]";:.<>,SPACE
│ 
│   with azuread_group.foo_bar,
│   on main.tf line 41, in resource "azuread_group" "foo_bar":
│   41:   mail_nickname            = "foo.bar"
│ 
╵
```

### Expected Behavior

It should work as "." is an allowed character. There are plenty of groups in our AAD like this.

### Actual Behavior

It fails because of the "." character in the `mail_nickname` field.

### Steps to Reproduce

1. `terraform apply`

**Comment by Threpio** [comment]
This is caused by this validation function:

https://github.com/hashicorp/terraform-provider-azuread/blob/6a216f27942db188c16f1929ffbcd92e01be659e/internal/validate/mail.go#L10

That is called in 1 (One) place that is the mail.nickname validation in the group resource:

https://github.com/hashicorp/terraform-provider-azuread/blob/6a216f27942db188c16f1929ffbcd92e01be659e/internal/services/groups/group_resource.go#L153

Why is this only validated in a single place and is the change as simple as removing the .from that validation function and fixing the tests.
